module.exports = {
  playlistId: 'playlist:ghost-games',
  name: 'Ghost Games',
  description: null,
  createdTime: '2018-10-10T18:09:20.867Z',
  coverImage: {
    imgixUrl: 'https://castle.imgix.net/file:17c20d0',
    height: 410,
    width: 304,
  },
  user: {
    userId: 'user:expo',
    name: 'Expo',
    username: 'expo',
    isReal: true,
    photo: null,
  },
  mediaItems: [
    {
      name: 'Robosquash',
      published: '2018-09-24T02:09:23.000Z',
      createdTime: '2018-09-24T10:20:00.923Z',
      updatedTime: '2018-11-01T01:46:27.094Z',
      instructions: null,
      description: null,
      mediaUrl: 'castle://raw.githubusercontent.com/schazers/badboxart/master/main.lua',
      mediaId: 'media:robosquash',
      jamVotingUrl: null,
      coverImage: {
        url: null,
        imgixUrl: 'https://castle.imgix.net/file:553ac7f',
        height: 512,
        width: 512,
      },
      user: {
        userId: 'user:schazers',
        name: 'Jason Riggs',
        username: 'schazers',
        isReal: true,
        photo: {
          imgixUrl: 'https://castle.imgix.net/file:563a2ff+ches3arxdk99',
          height: 888,
          width: 894,
        },
      },
    },
    {
      name: 'Circloid',
      published: null,
      createdTime: '2018-10-10T18:20:54.244Z',
      updatedTime: '2018-11-01T01:46:27.094Z',
      instructions: null,
      description: null,
      mediaUrl: 'https://raw.githubusercontent.com/terribleben/circloid/release/main.lua',
      mediaId: 'media:circloid',
      jamVotingUrl: null,
      coverImage: {
        url: null,
        imgixUrl: 'https://castle.imgix.net/file:5cc2f8d',
        height: 512,
        width: 512,
      },
      user: {
        userId: 'user:ben',
        name: 'Ben Roth',
        username: 'ben',
        isReal: true,
        photo: {
          imgixUrl: 'https://castle.imgix.net/file:aad41bc',
          height: 1200,
          width: 1200,
        },
      },
    },
    {
      name: 'Wat Do?',
      published: null,
      createdTime: '2018-10-10T18:32:25.816Z',
      updatedTime: '2018-11-01T01:46:27.094Z',
      instructions: null,
      description: 'A platformer for LD42',
      mediaUrl: 'https://raw.githubusercontent.com/nikki93/wat-do/master/main.lua',
      mediaId: 'media:wat-do',
      jamVotingUrl: null,
      coverImage: {
        url: null,
        imgixUrl: 'https://castle.imgix.net/file:559858c',
        height: 512,
        width: 512,
      },
      user: {
        userId: 'user:nikki',
        name: 'Nikhilesh Sigatapu',
        username: 'nikki',
        isReal: true,
        photo: {
          imgixUrl: 'https://castle.imgix.net/file:1e02045',
          height: 128,
          width: 128,
        },
      },
    },
    {
      name: 'andromeadow',
      published: null,
      createdTime: '2018-10-28T08:50:37.643Z',
      updatedTime: '2018-11-06T23:17:04.775Z',
      instructions: null,
      description: {
        rich:
          '{"object":"value","document":{"object":"document","data":{},"nodes":[{"object":"block","type":"line","data":{},"nodes":[{"object":"text","leaves":[{"object":"leaf","text":"my submission for procjam 2018","marks":[]}]}]},{"object":"block","type":"line","data":{},"nodes":[{"object":"text","leaves":[{"object":"leaf","text":"an automatic painting experience","marks":[]}]}]},{"object":"block","type":"line","data":{},"nodes":[{"object":"text","leaves":[{"object":"leaf","text":"please sit back and relax","marks":[]}]}]},{"object":"block","type":"line","data":{},"nodes":[{"object":"text","leaves":[{"object":"leaf","text":"restart for a different, but similar, experience","marks":[]}]}]}]}}',
      },
      mediaUrl:
        'https://raw.githubusercontent.com/nikki93/procjam-oct-2018/4fe417f846c5d752adcac59f56e64e823116dfe1/main.lua',
      mediaId: 'media:andromeadow',
      jamVotingUrl: null,
      coverImage: {
        url: null,
        imgixUrl: 'https://castle.imgix.net/file:14c7b23',
        height: 512,
        width: 512,
      },
      user: {
        userId: 'user:nikki',
        name: 'Nikhilesh Sigatapu',
        username: 'nikki',
        isReal: true,
        photo: {
          imgixUrl: 'https://castle.imgix.net/file:1e02045',
          height: 128,
          width: 128,
        },
      },
    },
    {
      name: 'Maze',
      published: null,
      createdTime: '2018-10-28T20:33:56.971Z',
      updatedTime: '2018-11-06T23:15:34.491Z',
      instructions: null,
      description: {
        rich:
          '{"object":"value","document":{"object":"document","data":{},"nodes":[{"object":"block","type":"line","data":{},"nodes":[{"object":"text","leaves":[{"object":"leaf","text":"Generates mazes","marks":[]}]}]}]}}',
      },
      mediaUrl: 'https://raw.githubusercontent.com/ccheever/procmaze/master/main.lua',
      mediaId: 'media:maze',
      jamVotingUrl: null,
      coverImage: {
        url: null,
        imgixUrl: 'https://castle.imgix.net/file:fbd8406',
        height: 512,
        width: 512,
      },
      user: {
        userId: 'user:ccheever',
        name: 'Charlie Cheever',
        username: 'ccheever',
        isReal: true,
        photo: {
          imgixUrl: 'https://castle.imgix.net/file:c9b85f2',
          height: 200,
          width: 201,
        },
      },
    },
    {
      name: 'triangle warz',
      published: null,
      createdTime: '2018-11-05T06:05:10.236Z',
      updatedTime: '2018-11-06T23:13:48.729Z',
      instructions: null,
      description: {
        rich:
          '{"object":"value","document":{"object":"document","data":{},"nodes":[{"object":"block","type":"line","data":{},"nodes":[{"object":"text","leaves":[{"object":"leaf","text":"example usage of the \'sync.lua\' multiplayer api","marks":[]}]}]},{"object":"block","type":"line","data":{},"nodes":[{"object":"text","leaves":[{"object":"leaf","text":"","marks":[]}]}]},{"object":"block","type":"line","data":{},"nodes":[{"object":"text","leaves":[{"object":"leaf","text":"this game is multiplayer so it\'s most fun if someone else is playing it at the same time! just have them visit the same URI.","marks":[]}]}]}]}}',
      },
      mediaUrl:
        'https://raw.githubusercontent.com/expo/ghost-multi/master/example_triangle_warz.lua',
      mediaId: 'media:triangle-warz',
      jamVotingUrl: null,
      coverImage: {
        url: null,
        imgixUrl: 'https://castle.imgix.net/file:a92929d',
        height: 512,
        width: 512,
      },
      user: {
        userId: 'user:nikki',
        name: 'Nikhilesh Sigatapu',
        username: 'nikki',
        isReal: true,
        photo: {
          imgixUrl: 'https://castle.imgix.net/file:1e02045',
          height: 128,
          width: 128,
        },
      },
    },
    {
      name: 'Endless Library',
      published: null,
      createdTime: '2018-10-28T21:29:43.797Z',
      updatedTime: '2018-11-06T23:04:16.371Z',
      instructions: null,
      description: {
        rich:
          '{"object":"value","document":{"object":"document","data":{},"nodes":[{"object":"block","type":"line","data":{},"nodes":[{"object":"text","leaves":[{"object":"leaf","text":"Endless Library generates rooms full of books and some other things. Explore the library forever.","marks":[]}]}]}]}}',
      },
      mediaUrl: 'http://raw.githubusercontent.com/terribleben/endless-library/release/main.lua',
      mediaId: 'media:endless-library+csdhnvr99iid',
      jamVotingUrl: null,
      coverImage: {
        url: null,
        imgixUrl: 'https://castle.imgix.net/file:afa7236',
        height: 512,
        width: 512,
      },
      user: {
        userId: 'user:ben',
        name: 'Ben Roth',
        username: 'ben',
        isReal: true,
        photo: {
          imgixUrl: 'https://castle.imgix.net/file:aad41bc',
          height: 1200,
          width: 1200,
        },
      },
    },
    {
      name: 'Quickdraw Blackjack',
      published: null,
      createdTime: '2018-12-17T05:23:03.674Z',
      updatedTime: '2018-12-17T23:37:26.443Z',
      instructions: null,
      description: null,
      mediaUrl: 'https://raw.githubusercontent.com/bridgs/quickdraw-blackjack/master/main.lua',
      mediaId: 'media:quickdraw-blackjack',
      jamVotingUrl: null,
      coverImage: {
        url: null,
        imgixUrl: 'https://castle.imgix.net/file:54a1459',
        height: 1320,
        width: 750,
      },
      user: {
        userId: 'user:bridgs',
        name: 'Ayla Myers',
        username: 'bridgs',
        isReal: true,
        photo: {
          imgixUrl: 'https://castle.imgix.net/file:c03926b',
          height: 400,
          width: 400,
        },
      },
    },
    {
      name: 'Gemzen',
      published: null,
      createdTime: '2018-12-17T23:26:30.586Z',
      updatedTime: '2018-12-17T23:55:49.440Z',
      instructions: null,
      description: null,
      mediaUrl: 'https://raw.githubusercontent.com/revillo/castle-games/master/gemzen.lua',
      mediaId: 'media:gemzen',
      jamVotingUrl: null,
      coverImage: {
        url: null,
        imgixUrl: 'https://castle.imgix.net/file:17c20d0',
        height: 410,
        width: 304,
      },
      user: {
        userId: 'user:revillo',
        name: 'Oliver Castaneda',
        username: 'revillo',
        isReal: true,
        photo: null,
      },
    },
  ],
};
