#!/usr/bin/env sh
export PGHOST=`node -e "console.log(require('./src/utils/secret').postgres.host)"` 
export PGUSER=`node -e "console.log(require('./src/utils/secret').postgres.user)"` 
export PGDATABASE=`node -e "console.log(require('./src/utils/secret').postgres.database)"` 
export PGPASSWORD=`node -e "console.log(require('./src/utils/secret').postgres.password)"`

echo "// Ghost Database"
echo 'Type \dt to list tables, \d+ <table-name> to describe a table'
pgcli  --host=$PGHOST --user=$PGUSER --dbname=$PGDATABASE $*


