#!/usr/bin/env sh
export PGHOST=`node -e "console.log(require('./secret').postgres.host)"` 
export PGUSER=`node -e "console.log(require('./secret').postgres.user)"` 
export PGDATABASE=`node -e "console.log(require('./secret').postgres.database)"` 
export PGPASSWORD=`node -e "console.log(require('./secret').postgres.password)"`

pg_dump  --host=$PGHOST --user=$PGUSER --dbname=$PGDATABASE $*


