await model.newUserAsync({userId: 'user:adam', location: 'Redwood City', name: 'Adam Perry', username: 'anp'});
await model.newUserAsync({userId: "user:jesse", location: "Seattle", name: "Jesse Ruder", username: 'jesse' });
await model.newUserAsync({userId: 'user:quin', name: 'Quinlan Jung', location: 'Palo Alto', username: 'sushipower'});
await model.newUserAsync({userId: 'user:eric', location: 'Mountain View', name: 'Eric Samelson', username: 'eric'});
await model.newUserAsync({userId: 'user:brent', location: 'Vancouver', name: 'Brent Vatne', username: 'brent'});
await model.newUserAsync({userId: 'user:jess', name: 'Jess Moore', location: 'San Francisco', username: 'jess'});
await model.newUserAsync({userId: 'user:nikki', location: 'San Francisco', name: 'Nikhilesh Sigatapu', username: 'nikki'});
await model.newUserAsync({userId: 'user:jim', location: 'San Francisco', name: 'Jim Lee', username: 'jim'});
await model.newUserAsync({userId: 'user:ville', name: 'Ville Immonen', location: 'Helsinki', username: 'fson'});
await model.newUserAsync({userId: 'user:ide', name: 'James Ide', location: 'Palo Alto', username: 'ide'});
await model.newUserAsync({userId: 'user:a-nav', location: 'Milwaukee', name: 'Adam Navarro', username: 'a-nav'});
await model.newUserAsync({userId: 'user:evan', name: 'Evan Bacon', location: 'Palo Alto', username: 'evan'});
await model.newUserAsync({userId: 'user:tc', name: 'TC Davis', location: 'San Francisco', username: 'tc'});
await model.newUserAsync({userId: 'user:ccheever', name:'Charlie Cheever', location: 'Palo Alto', username: 'ccheever'});
await model.newUserAsync({userId: 'user:nick', name: 'Nick Novitski', location: 'San Francisco', username: 'nick'});
await model.newUserAsync({userId: 'user:schazers', name: 'Jason Riggs', location: "San Francisco", username: 'schazers'});
await model.newUserAsync({userId: 'user:ben', name: 'Ben Roth', location: 'Seattle', username: 'ben'});
